/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javadev_module5;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
